// This is the root layout of the application

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import NavbarContainer from "@/components/NavbarContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarContainer>
          {/**
           * 1) This is another way around to type as {props.children}
           * 2) Best practice is to write like this
           * 3) Reason - NavbarContainer treat as a CSR and Navbar treat as SSR
           */}
          <Navbar />
        </NavbarContainer>
        {children}
      </body>
    </html>
  );
}
